config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks' }
  
  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end

    unauthenticated :user do
      root 'users/sessions#new', as: :unauthenticated_root
    end
  end

  resources :posts, only: [:index, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  resources :friendships, only: [:create, :destroy, :update]
  
  resources :users, only: [:index, :show] do
    resource :profile, only: [:show, :update]
    resource :detail, only: [:new, :create, :edit, :update]
  end
end

app/models/age.rb
class Age < ApplicationRecord
  belongs_to :detail
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body, presence: true
end

app/models/contact_information.rb
class ContactInformation < ApplicationRecord
end

app/models/description.rb
class Description < ApplicationRecord
  belongs_to :describable, polymorphic: true

  validates :body, presence: true, length: { maximum: 500 }
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :profile

  has_one :location, dependent: :destroy
  has_one :age, dependent: :destroy
  has_one :contact_information, dependent: :destroy
  has_one :gender, dependent: :destroy
  has_one :name, dependent: :destroy

  accepts_nested_attributes_for :location
  accepts_nested_attributes_for :age
  accepts_nested_attributes_for :contact_information
  accepts_nested_attributes_for :gender
  accepts_nested_attributes_for :name
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'

  validates :user_id, uniqueness: { scope: :friend_id }
end

app/models/gender.rb
class Gender < ApplicationRecord
  belongs_to :detail
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :detail

  validates :address, length: { maximum: 100 }
  validates :state, length: { maximum: 50 }
  validates :city, length: { maximum: 50 }
  validates :country, length: { maximum: 50 }
  validates :zip, length: { maximum: 10 }
end

app/models/name.rb
class Name < ApplicationRecord
  belongs_to :detail

  validates :fname, presence: true, length: { in: 1..24 }
  validates :lname, presence: true, length: { in: 1..24 }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :body, presence: true

  def liked?(user)
    !!self.likes.find{ |like| like.user_id == user.id }
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  has_one :detail, dependent: :destroy
  has_one_attached :avatar, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  
  devise :omniauthable, omniauth_providers: %i[facebook]

  validates :username, presence: true, length: { in: 3..24 }

  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy


  has_many :pending_friendships, -> { where(active: false) },
    class_name: 'Friendship', dependent: :destroy
  has_many :pending_friends, through: :pending_friendships, source: :friend,
    dependent: :destroy
  
  has_many :accepted_friendships, -> { where(active: true) },
    class_name: 'Friendship', dependent: :destroy
  has_many :accepted_friends, through: :accepted_friendships, source: :friend,
    dependent: :destroy


  has_many :inverse_pending_friendships, -> { where(active: false) },
    class_name: 'Friendship', foreign_key: 'friend_id', dependent: :destroy
  has_many :inverse_pending_friends, through: :inverse_pending_friendships,
    source: :user

  has_many :inverse_accepted_friendships, -> { where(active: true) },
    class_name: 'Friendship', foreign_key: 'friend_id', dependent: :destroy
  has_many :inverse_accepted_friends, through: :inverse_accepted_friendships,
    source: :user

  has_one :profile, dependent: :destroy

  def self.from_omniauth(auth)
    full_name = auth.info.name.split(" ")

    created_user = where(provider: auth.provider, uid: auth.uid).first_or_create! do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = "#{full_name[0]}_#{full_name[1]}_#{rand(1..999)}"

      user.skip_confirmation!
    end

    unless created_user.profile
      created_user.create_profile
      created_user.profile.create_detail
      created_user.profile.detail.create_age
      created_user.profile.detail.create_location
      created_user.profile.detail.create_gender
      created_user.profile.detail.create_contact_information
      created_user.profile.detail.create_name(fname: full_name[0], lname:full_name[1])
    end

    created_user
  end

  def sent_invitation?(user, friend)
    !!self.pending_friendships.find do |invite|
      invite.user_id == user.id && invite.friend_id == friend.id
    end
  end

  def receive_invitation?(user, friend)
    !!self.inverse_pending_friendships.find do |invite|
      invite.friend_id == user.id && invite.active == false
    end
  end

  def friend?(user, friend)
    !!Friendship.find_by(active: true, user: user, friend: friend) ||
    !!Friendship.find_by(active: true, user: friend, friend: user)
  end

  def is_friend_of(user, friend)
    @friendship = self.accepted_friendships
      .find_by(active: true, user: user, friend: friend)

    @friendship = self.inverse_accepted_friendships
      .find_by(active: true, user: friend, friend: user) if @friendship.nil?

    @friendship
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @profile = User.find(params[:user_id]).profile
  end

  def update
    @profile = current_user.profile

    if @profile.update(profile_params)
      flash[:success] = 'Profile picture uploaded.'
      redirect_to user_profile_path(current_user)
    else
      flash[:error] = 'Failed to upload profile picture.'
      redirect_to user_profile_path(current_user)
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/profiles/_list_information.html.erb
<div class='columns'>
  <span class='column is-8'><strong>Name</strong></span>
  <span class='column'><%= @profile.detail.name.fname %> <%= @profile.detail.name.lname %></span>
</div>

<div class='columns'>
  <span class='column is-8'><strong>Age</strong></span>
  <span class='column'><%= @profile.detail.age.dob %></span>
</div>

<div class='columns'>
  <span class='column is-8'><strong>Gender</strong></span>
  <span class='column'><%= @profile.detail.gender.gender %><br></span>
</div>

<div class='columns'>
  <span class='column is-8'><strong>Country</strong></span>
  <span class='column'><%= @profile.detail.location.country %></span>
</div>

<div class='columns'>
  <span class='column is-8'><strong>State</strong></span>
  <span class='column'><%= @profile.detail.location.state %></span>
</div>

<div class='columns'>
  <span class='column is-8'><strong>Address</strong></span>
  <span class='column'><%= @profile.detail.location.address %></span>
</div>

<div class='columns'>
  <span class='column is-8'><strong>Zip code</strong></span>
  <span class='column'><%= @profile.detail.location.zip %></span>
</div>

<div class='columns'>
  <span class='column is-8'><strong>Phone Number</strong></span>
  <span class='column'><%= @profile.detail.contact_information.phone_number %></span>
</div>

app/views/profiles/_profile_pic_upload.html.erb
<%= form_with model: @profile, url: user_profile_path(current_user), method: :put do |f| %>
  <div class='field'>
    <%= f.file_field :avatar %>
  </div>

  <div class='field actions'>
    <%= f.submit 'Upload', class: 'button is-info is-outlined' %>
  </div>
<% end %>

app/views/profiles/show.html.erb
<section class='section'>
  <div class='container box'>

    <h1 class='title is-1'>Personal Information</h1>
    
    <div class='container box'>
      <div class='block'>
        <% if current_user.profile.avatar.attached? %>
          <%= image_tag(current_user.profile.avatar.variant(resize: '100x100'), size: '100') %>
        <% else %>
          <%= image_tag 'unknown.jpg' %>
        <% end %>
      </div>

      <div class='block'>
        <span class='title is-3'>Profile Picture</span>
      </div>

      <div class='block'>
        <%= render 'profile_pic_upload' %>
      </div>
    </div>

    <%= render 'list_information' %>

    <%= link_to 'Edit profile', edit_user_detail_path(current_user), class: 'button' %>
  </div>
</section>