config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks' }
  
  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end

    unauthenticated :user do
      root 'users/sessions#new', as: :unauthenticated_root
    end
  end

  resources :posts, only: [:index, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  resources :friendships, only: [:create, :destroy, :update]
  
  resources :users, only: [:index, :show] do
    resource :profile, only: [:show, :update]
    resource :detail, only: [:new, :create, :edit, :update]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  
  devise :omniauthable, omniauth_providers: %i[facebook]

  validates :username, presence: true, length: { in: 3..24 }

  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy


  has_many :pending_friendships, -> { where(active: false) },
    class_name: 'Friendship', dependent: :destroy
  has_many :pending_friends, through: :pending_friendships, source: :friend,
    dependent: :destroy
  
  has_many :accepted_friendships, -> { where(active: true) },
    class_name: 'Friendship', dependent: :destroy
  has_many :accepted_friends, through: :accepted_friendships, source: :friend,
    dependent: :destroy


  has_many :inverse_pending_friendships, -> { where(active: false) },
    class_name: 'Friendship', foreign_key: 'friend_id', dependent: :destroy
  has_many :inverse_pending_friends, through: :inverse_pending_friendships,
    source: :user

  has_many :inverse_accepted_friendships, -> { where(active: true) },
    class_name: 'Friendship', foreign_key: 'friend_id', dependent: :destroy
  has_many :inverse_accepted_friends, through: :inverse_accepted_friendships,
    source: :user

  has_one :profile, dependent: :destroy

  def self.from_omniauth(auth)
    full_name = auth.info.name.split(" ")

    created_user = where(provider: auth.provider, uid: auth.uid).first_or_create! do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = "#{full_name[0]}_#{full_name[1]}_#{rand(1..999)}"

      user.skip_confirmation!
    end

    unless created_user.profile
      created_user.create_profile
      created_user.profile.create_detail
      created_user.profile.detail.create_age
      created_user.profile.detail.create_location
      created_user.profile.detail.create_gender
      created_user.profile.detail.create_contact_information
      created_user.profile.detail.create_name(fname: full_name[0], lname:full_name[1])
    end

    created_user
  end

  def sent_invitation?(user, friend)
    !!self.pending_friendships.find do |invite|
      invite.user_id == user.id && invite.friend_id == friend.id
    end
  end

  def receive_invitation?(user, friend)
    !!self.inverse_pending_friendships.find do |invite|
      invite.friend_id == user.id && invite.active == false
    end
  end

  def friend?(user, friend)
    !!Friendship.find_by(active: true, user: user, friend: friend) ||
    !!Friendship.find_by(active: true, user: friend, friend: user)
  end

  def is_friend_of(user, friend)
    @friendship = self.accepted_friendships
      .find_by(active: true, user: user, friend: friend)

    @friendship = self.inverse_accepted_friendships
      .find_by(active: true, user: friend, friend: user) if @friendship.nil?

    @friendship
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token, only: :create

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in @user
      redirect_to authenticated_root_path, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra)
      redirect_to unauthenticated_root_path
    end
  end

  def failure
    redirect_to unauthenticated_root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  after_action :generate_profile, only: [:create]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute, :username])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    new_user_detail_path(current_user)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    new_user_detail_path(current_user)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(username: :asc)
      .includes(:pending_friendships, :inverse_pending_friendships)

    @result = User.where('username LIKE ?', "%#{params[:query]}%")
      .order(username: :asc).includes(:pending_friendships, :inverse_pending_friendships) if params[:query]
  end

  def show
    @user = User.find(params[:id])

    @posts = Post
      .where(user: @user)
      .includes(:user, { user: { profile: { detail: :name }}}, :likes,
                :comments, { comments: { user: { profile: { detail: :name, avatar_attachment: :blob }}}})
      .order(created_at: :desc)
    
    @post = Post.new
    @comment = Comment.new
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_buttons.html.erb
<div class='field is-grouped'>
  <%= link_to user_path(user), class: 'button is-info is-rounded mr-3' do %>
    <%= icon('fas', 'user') %>&nbsp;&nbsp;Profile
  <% end %>

  <% if current_user.sent_invitation?(current_user, user) %>
    <%= button_to friendships_path, class: 'button is-info is-rounded', disabled: true, params: { friend: user } do %>
      <%= icon('fas', 'user-plus') %>&nbsp;&nbsp;Add Friend
    <% end %>
  
  <% elsif current_user.receive_invitation?(current_user, user) && current_user.inverse_pending_friendships.where(user: user, friend: current_user).exists? %>
    <%= button_to friendship_path(current_user.inverse_pending_friendships.where(user: user, friend: current_user).first),
                   method: :put, class: 'button is-success is-rounded' do %>
      <%= icon('fas', 'user-plus') %>&nbsp;&nbsp;Accept request
    <% end %>

  <% elsif !current_user.friend?(current_user, user) %>
    <%= button_to friendships_path, class: 'button is-info is-rounded', params: { friend: user } do %>
      <%= icon('fas', 'user-plus') %>&nbsp;&nbsp;Add Friend
    <% end %>

  <% elsif current_user.friend?(current_user, user) %>
    <%= button_to friendship_path(current_user.is_friend_of(current_user, user)),
                  method: :delete, class: 'button is-danger is-rounded' do %>
      <%= icon('fas', 'user-minus') %>&nbsp;&nbsp;Delete friend
    <% end %>
  <% end %>
</div>

app/views/users/_list_users.html.erb
<% list.each do |user| %>
  <% next if current_user == user %>

  <div class='container box'>
    <div class='columns is-vcentered is-mobile' id='pbox'>
      <div class='column'>
        <div class='columns is-vcentered is-mobile'>
          <div class='column is-narrow'>
            <% if user.profile.avatar.attached? %>
              <%= image_tag user.profile.avatar.variant(resize: '80x80'), size: '80' %>
            <% else %>
              <%= image_tag 'unknown.jpg', size: '80' %>
            <% end %>
          </div>
          <div class='column is-narrow'>
            <h2 class='subtitle is-4 mb-0'>
              <strong>
                <%= user.profile.detail.name.fname %>
                <%= user.profile.detail.name.lname %>
              </strong>
            </h2>

            <h3 class='subtitle is-6'>
              @<%= user.username %>
            </h3>
          </div>
        </div>
      </div>

      <div class='column is-narrow'>
        <%= render 'buttons', user: user %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_search_form.html.erb
<div class='block'>
  <%= form_with url: users_path, method: :get do |f| %>
    <div class='column control is-3 p-0'>
      <%= f.text_field :query, placeholder: 'Search for friend', class: 'input'%>
    </div>
  <% end %>
</div>

app/views/users/_user_profile.html.erb
<section class='section'>
  <div class='container box'>
    <div class='columns is-multiline'>
      <div class='column'>
        <figure class='image is-128x128'>
          <% if @user.profile.avatar.attached? %>
            <%= image_tag @user.profile.avatar.variant(resize: '128x128'), class: 'is-rounded' %>
          <% else %>
            <%= image_tag 'unknown.jpg', size: '150' %>
          <% end %>
        </figure>
      </div>

      <div class='column'>
        <h1 class='title is-4 mb-0'>
          <%= @user.profile.detail.name.fname %> <%= @user.profile.detail.name.lname %>
        </h1>

        <h2 class='subtitle is-6 mt-0'>
          @<%= @user.username %>
        </h2>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section class='section'>
  <div class='block container'>
    <div class='block'>
      <h1 class='title is-1'>User List</h1>
    </div>

    <div class='block'>
      <%= render 'search_form' %>
    </div>
  </div>

  <div class='block'>
    <% if params[:query] %>
      <%= render 'list_users', list: @result %>
    <% else%>
      <%= render 'list_users', list: @users %>
    <% end %>
  </div>
</section>

app/views/users/show.html.erb
<div class='columns'>
  <div class='column is-one-fifth'>
    <%= render 'user_profile' %>
  </div>

  <div class='column'>
    <%= render 'shared/posts/create_post', post: @post %>

    <section class='section'>
      <div class='container mb-3'>
        <h2 class='title is-4'>Your Posts</h2>
      </div>

      <%=  render 'shared/posts/list_posts', posts: @posts %>
    </section>
  </div>

  <div class='column is-one-fifth'>
</div>