config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks' }
  
  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end

    unauthenticated :user do
      root 'users/sessions#new', as: :unauthenticated_root
    end
  end

  resources :posts, only: [:index, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  resources :friendships, only: [:create, :destroy, :update]
  
  resources :users, only: [:index, :show] do
    resource :profile, only: [:show, :update]
    resource :detail, only: [:new, :create, :edit, :update]
  end
end

app/models/age.rb
class Age < ApplicationRecord
  belongs_to :detail
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body, presence: true
end

app/models/description.rb
class Description < ApplicationRecord
  belongs_to :describable, polymorphic: true

  validates :body, presence: true, length: { maximum: 500 }
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :profile

  has_one :location, dependent: :destroy
  has_one :age, dependent: :destroy
  has_one :contact_information, dependent: :destroy
  has_one :gender, dependent: :destroy
  has_one :name, dependent: :destroy

  accepts_nested_attributes_for :location
  accepts_nested_attributes_for :age
  accepts_nested_attributes_for :contact_information
  accepts_nested_attributes_for :gender
  accepts_nested_attributes_for :name
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'

  validates :user_id, uniqueness: { scope: :friend_id }
end

app/models/gender.rb
class Gender < ApplicationRecord
  belongs_to :detail
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :detail

  validates :address, length: { maximum: 100 }
  validates :state, length: { maximum: 50 }
  validates :city, length: { maximum: 50 }
  validates :country, length: { maximum: 50 }
  validates :zip, length: { maximum: 10 }
end

app/models/name.rb
class Name < ApplicationRecord
  belongs_to :detail

  validates :fname, presence: true, length: { in: 1..24 }
  validates :lname, presence: true, length: { in: 1..24 }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :body, presence: true

  def liked?(user)
    !!self.likes.find{ |like| like.user_id == user.id }
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  has_one :detail, dependent: :destroy
  has_one_attached :avatar, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  
  devise :omniauthable, omniauth_providers: %i[facebook]

  validates :username, presence: true, length: { in: 3..24 }

  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy


  has_many :pending_friendships, -> { where(active: false) },
    class_name: 'Friendship', dependent: :destroy
  has_many :pending_friends, through: :pending_friendships, source: :friend,
    dependent: :destroy
  
  has_many :accepted_friendships, -> { where(active: true) },
    class_name: 'Friendship', dependent: :destroy
  has_many :accepted_friends, through: :accepted_friendships, source: :friend,
    dependent: :destroy


  has_many :inverse_pending_friendships, -> { where(active: false) },
    class_name: 'Friendship', foreign_key: 'friend_id', dependent: :destroy
  has_many :inverse_pending_friends, through: :inverse_pending_friendships,
    source: :user

  has_many :inverse_accepted_friendships, -> { where(active: true) },
    class_name: 'Friendship', foreign_key: 'friend_id', dependent: :destroy
  has_many :inverse_accepted_friends, through: :inverse_accepted_friendships,
    source: :user

  has_one :profile, dependent: :destroy

  def self.from_omniauth(auth)
    full_name = auth.info.name.split(" ")

    created_user = where(provider: auth.provider, uid: auth.uid).first_or_create! do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = "#{full_name[0]}_#{full_name[1]}_#{rand(1..999)}"

      user.skip_confirmation!
    end

    unless created_user.profile
      created_user.create_profile
      created_user.profile.create_detail
      created_user.profile.detail.create_age
      created_user.profile.detail.create_location
      created_user.profile.detail.create_gender
      created_user.profile.detail.create_contact_information
      created_user.profile.detail.create_name(fname: full_name[0], lname:full_name[1])
    end

    created_user
  end

  def sent_invitation?(user, friend)
    !!self.pending_friendships.find do |invite|
      invite.user_id == user.id && invite.friend_id == friend.id
    end
  end

  def receive_invitation?(user, friend)
    !!self.inverse_pending_friendships.find do |invite|
      invite.friend_id == user.id && invite.active == false
    end
  end

  def friend?(user, friend)
    !!Friendship.find_by(active: true, user: user, friend: friend) ||
    !!Friendship.find_by(active: true, user: friend, friend: user)
  end

  def is_friend_of(user, friend)
    @friendship = self.accepted_friendships
      .find_by(active: true, user: user, friend: friend)

    @friendship = self.inverse_accepted_friendships
      .find_by(active: true, user: friend, friend: user) if @friendship.nil?

    @friendship
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class='has-background-light'>
  <head>
    <title>Kaobook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <% flash.each do |type, msg| %>
      <%= type %>: <%= msg %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class='navbar has-background-dark' role='navigation'>
  <div class='navbar-brand'>
    <% if user_signed_in? %>
      <%= link_to 'Homepage', authenticated_root_path, class: 'navbar-item title is-3 has-text-white' %>
    <% else %>
      <%= link_to 'Homepage', unauthenticated_root_path, class: 'navbar-item title is-3 has-text-white' %>
    <% end %>
  </div>

  <div class='navbar-menu'>
    <div class='navbar-start'>
      <% if user_signed_in? %>
        <div class='navbar-item'>
          <%= link_to 'Users', users_path, class: 'button is-dark' %>
        </div>

        <div class='navbar-item'>
          <%= link_to 'Personal Page', user_path(current_user), class: 'button is-dark' %>
        </div>

        <div class='navbar-item'>
          <%= link_to 'Profile', user_profile_path(current_user), class: 'button is-dark' %>
        </div>
      <% end %>
    </div>

    <div class='navbar-end'>

      <% if user_signed_in? %>
        <div class='navbar-item'>
          <%= render 'shared/notifications' %>
        </div>
      <% end %>

      <% if user_signed_in? %>
        <div class='navbar-item has-text-white'>
          logged in:&nbsp;&nbsp;<%= current_user.username %>
        </div>
      <% end %>

      <div class='navbar-item buttons'>
        <% if user_signed_in? %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'button is-danger is-outlined' %>
        <% else %>
          <%= link_to 'Login', new_user_session_path, class: 'button is-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_notifications.html.erb
<div class='dropdown is-right is-hoverable'>
  <div class='dropdown-trigger'>
    <button class='button has-background-dark has-text-white'>
      <span>Notifications</span>
    </button>
  </div>

  <div class='dropdown-menu nav-dropdown' id='dropdown-menu'>
    <div class='dropdown-content'>
      <% if @requests.empty? %>
        <div class='dropdown-item'>
          <div>
            <span class='subtitle is-6'>No incoming friend requests</span>
          </div>
        </div>
      <% else %>
        <% @requests.each do |request| %>
          <div class='dropdown-item'>
            <div class='columns'>
              <div class='column'>
                <span class='subtitle is-6'><strong><%= request.user.username %></strong> wants to be your friend.</span>
              </div>

              <div class='column is-narrow'>
                <div class='field is-grouped '>
                  <%= button_to friendship_path(request), method: :put, class: 'button is-small is-success' do %>
                    <span class='icon'><%= icon('fas', 'check') %></span>
                  <% end %>

                  &nbsp;&nbsp;

                  <%= button_to friendship_path(request), method: :delete, class: 'button is-small is-danger' do %>
                    <span class='icon'><%= icon('fas', 'times') %></span>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <hr class='dropdown-divider'>
        <% end %>
      <% end %>
    </div>

  </div>
</div>