config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks' }
  
  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end

    unauthenticated :user do
      root 'users/sessions#new', as: :unauthenticated_root
    end
  end

  resources :posts, only: [:index, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  resources :friendships, only: [:create, :destroy, :update]
  
  resources :users, only: [:index, :show] do
    resource :profile, only: [:show, :update]
    resource :detail, only: [:new, :create, :edit, :update]
  end
end

app/models/age.rb
class Age < ApplicationRecord
  belongs_to :detail
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body, presence: true
end

app/models/contact_information.rb
class ContactInformation < ApplicationRecord
end

app/models/description.rb
class Description < ApplicationRecord
  belongs_to :describable, polymorphic: true

  validates :body, presence: true, length: { maximum: 500 }
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :profile

  has_one :location, dependent: :destroy
  has_one :age, dependent: :destroy
  has_one :contact_information, dependent: :destroy
  has_one :gender, dependent: :destroy
  has_one :name, dependent: :destroy

  accepts_nested_attributes_for :location
  accepts_nested_attributes_for :age
  accepts_nested_attributes_for :contact_information
  accepts_nested_attributes_for :gender
  accepts_nested_attributes_for :name
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'

  validates :user_id, uniqueness: { scope: :friend_id }
end

app/models/gender.rb
class Gender < ApplicationRecord
  belongs_to :detail
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :detail

  validates :address, length: { maximum: 100 }
  validates :state, length: { maximum: 50 }
  validates :city, length: { maximum: 50 }
  validates :country, length: { maximum: 50 }
  validates :zip, length: { maximum: 10 }
end

app/models/name.rb
class Name < ApplicationRecord
  belongs_to :detail

  validates :fname, presence: true, length: { in: 1..24 }
  validates :lname, presence: true, length: { in: 1..24 }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :body, presence: true

  def liked?(user)
    !!self.likes.find{ |like| like.user_id == user.id }
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  has_one :detail, dependent: :destroy
  has_one_attached :avatar, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  
  devise :omniauthable, omniauth_providers: %i[facebook]

  validates :username, presence: true, length: { in: 3..24 }

  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy


  has_many :pending_friendships, -> { where(active: false) },
    class_name: 'Friendship', dependent: :destroy
  has_many :pending_friends, through: :pending_friendships, source: :friend,
    dependent: :destroy
  
  has_many :accepted_friendships, -> { where(active: true) },
    class_name: 'Friendship', dependent: :destroy
  has_many :accepted_friends, through: :accepted_friendships, source: :friend,
    dependent: :destroy


  has_many :inverse_pending_friendships, -> { where(active: false) },
    class_name: 'Friendship', foreign_key: 'friend_id', dependent: :destroy
  has_many :inverse_pending_friends, through: :inverse_pending_friendships,
    source: :user

  has_many :inverse_accepted_friendships, -> { where(active: true) },
    class_name: 'Friendship', foreign_key: 'friend_id', dependent: :destroy
  has_many :inverse_accepted_friends, through: :inverse_accepted_friendships,
    source: :user

  has_one :profile, dependent: :destroy

  def self.from_omniauth(auth)
    full_name = auth.info.name.split(" ")

    created_user = where(provider: auth.provider, uid: auth.uid).first_or_create! do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = "#{full_name[0]}_#{full_name[1]}_#{rand(1..999)}"

      user.skip_confirmation!
    end

    unless created_user.profile
      created_user.create_profile
      created_user.profile.create_detail
      created_user.profile.detail.create_age
      created_user.profile.detail.create_location
      created_user.profile.detail.create_gender
      created_user.profile.detail.create_contact_information
      created_user.profile.detail.create_name(fname: full_name[0], lname:full_name[1])
    end

    created_user
  end

  def sent_invitation?(user, friend)
    !!self.pending_friendships.find do |invite|
      invite.user_id == user.id && invite.friend_id == friend.id
    end
  end

  def receive_invitation?(user, friend)
    !!self.inverse_pending_friendships.find do |invite|
      invite.friend_id == user.id && invite.active == false
    end
  end

  def friend?(user, friend)
    !!Friendship.find_by(active: true, user: user, friend: friend) ||
    !!Friendship.find_by(active: true, user: friend, friend: user)
  end

  def is_friend_of(user, friend)
    @friendship = self.accepted_friendships
      .find_by(active: true, user: user, friend: friend)

    @friendship = self.inverse_accepted_friendships
      .find_by(active: true, user: friend, friend: user) if @friendship.nil?

    @friendship
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @friends = current_user.accepted_friends + current_user.inverse_accepted_friends
    @friends << current_user

    @posts = Post
      .where(user_id: @friends)
      .includes(:user, { user: { profile: { detail: :name }}},
                :likes,
                :comments, { comments: { user: { profile: { detail: :name, avatar_attachment: :blob }}}})
      .order(created_at: :desc)

    @post = Post.new
    @comment = Comment.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:succes] = 'Post successful'
      redirect_to posts_path
    else
      flash[:error] = 'Post must contain something.'
      redirect_to posts_path
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    
    flash[:success] = 'Post deleted.'
    redirect_to posts_path
  end

  private
  
  def post_params
    params.require(:post).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/index.html.erb
<%# Create a post section %>
<%= render 'shared/posts/create_post', post: @post %>

<section class='section'>
  <div class='container mb-3'>
    <h2 class='title is-4'>Your Timeline</h1>
  </div>

  <%= render 'shared/posts/list_posts', posts: @posts %>
</section>

app/views/shared/posts/_create_comments.html.erb
<section class='section'>
  <div class='container'>
    <h3 class='title is-6'>Post a comment</h3>

    <%= form_with model: @comment, url: post_comments_path(post) do |f| %>
      <div class='field'>
        <div class='control'>
          <%= f.text_area :body, class: 'textarea', placeholder: 'Comment here' %>
        </div>
      </div>

      <div class='action'>
        <%= f.submit 'Comment', class: 'button is-primary is-outlined' %>
      </div>
    <% end %>
  </div>
</section>

app/views/shared/posts/_create_post.html.erb
<section class='section'>
  <div class='container box'>
    <h1 class='title is-4'>New post</h1>
    <%= form_with model: post do |f| %>
      <div class='field'>
        <div class='control'>
          <%= f.text_area :body, class: 'textarea', placeholder: 'e.g. What are you thinking?' %>
        </div>
      </div>

      <div class='actions'>
        <%= f.submit 'Post', autofocus: true, class: 'button is-success is-outlined' %>
      </div>
    <% end %>
  </div>
</section>

app/views/shared/posts/_list_posts.html.erb
<% posts.each do |post| %>
  <div class='container box'>
    <div class=columns>
      <%= render 'shared/posts/post_user_details', post: post %>

      <%= render 'shared/posts/post_dropdown', post: post %>
    </div>

    <section class='section'>
      <div class='block'>
        <p><%= post.body %></p>
      </div>
    </section>
    
    <section class='section'>
      <div class='container'>
        <%= render 'shared/posts/post_likes', post: post %>

        <%= render 'shared/posts/post_comments', post: post %>
      </div>
    </section>

    <%= render 'shared/posts/create_comments', post: post %>
  </div>
<% end %>

app/views/shared/posts/_post_comments.html.erb
<div class='block'>
  <% if post.comments.empty? %>
    <h3 class='title is-6'>No comments</h3>
  <% else %>
    <h3 class='title is-6'>Comments</h3>

    <% post.comments.each do |comment| %>
      <div class= 'container box'>
        <div class='columns'>
          <div class='column'>
            <p>
              <div class='columns'>
                <div class='column pr-2'>
                  <%= render 'shared/posts/user_pic', item: comment, size: '80', dim: '80x80' %>
                </div>

                <div class='column is-four-fifths pl-2'>
                  <h4 class='block subtitle is-6 mb-1'>
                    <strong>
                      <%= comment.user.profile.detail.name.fname %>
                      <%= comment.user.profile.detail.name.lname %>
                    </strong>
                  </h4>
                  
                  <p class='block'>
                    <%= comment.body %>
                  </p>
                </div>

                <div class='column is-narrow'>
                  <% if comment.user == current_user %>
                    <%= link_to 'delete', post_comment_path(post, comment), method: :delete, class: 'button is-danger is-small is-outlined' %>
                  <% end %>
                </div>

              </div>
          </div>

        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/posts/_post_dropdown.html.erb
<div class='column is-1'>
  <div class='dropdown is-hoverable is-right'>
    <div class='dropdown-trigger'>
      <button class='button is-inverted'>
        <span class='icon is-small'><%= icon('fas', 'ellipsis-v') %></span>
      </button>
    </div>

    <div class='dropdown-menu'>
      <div class='dropdown-content'>
        <div class='dropdown-item'>
          <%= link_to 'Delete post', post_path(post), method: :delete, class: 'button is-danger is-inverted' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/posts/_post_likes.html.erb
<div class='block'>
  <% if post.liked?(current_user) %>
    <%= button_to post_like_path(post, post.likes.find{|like| like.user_id == current_user.id}), method: :delete, class: 'button is-danger is-outlined' do %>
      <%= icon('far', 'thumbs-up') %>&nbsp;&nbsp;<%= post.likes.size %>
    <% end%>
  <% else %>
    <%= button_to post_likes_path(post), class: 'button is-info is-outlined' do %>
      <%= icon('far', 'thumbs-up') %>&nbsp;&nbsp;<%= post.likes.size %>
    <% end%>
  <% end %>
</div>

app/views/shared/posts/_post_user_details.html.erb
<div class='column is-11'>
  <div class='columns'>
    <span class='column is-1'>
      <%= render 'shared/posts/user_pic', item: post, size: '100', dim: '100x100' %>
    </span>

    <span class='column is-11'>
      <h2 class='title is-3 mb-0 '><%= post.user.profile.detail.name.fname %>
                                   <%= post.user.profile.detail.name.lname %></h2>
      <p class='subtitle is-6 mt-0 mb-0'>@<%= post.user.username %></p>
      <span>posted on: <%= post.created_at.to_formatted_s(:long) %></span>
    </span>
  </div>
</div>

app/views/shared/posts/_post_user_pic.html.erb
<% if item.user.profile.avatar.attached? %>
  <%= image_tag(item.user.profile.avatar.variant(resize: dim), size: size) %>
<% else %>
  <%= image_tag 'unknown.jpeg', size: size %>
<% end %>

app/views/shared/posts/_user_pic.html.erb
<% if item.user.profile.avatar.attached? %>
  <%= image_tag(item.user.profile.avatar.variant(resize: dim), size: size, alt: 'Profile picture') %>
<% else %>
  <%= image_tag 'unknown.jpg', alt: 'Profile picture', size: size %>
<% end %>